Make source code compatible with cpp+14, since win build was broken due to error C2872 (https://developercommunity.visualstudio.com/content/problem/93889/error-c2872-byte-ambiguous-symbol.html). Also added precompiled tree-sitter.lib